// Code.gs - server-side for Apps Script
const OPENAI_KEY_PROP = 'OPENAI_KEY';
const SPREADSHEET_ID_PROP = 'SPREADSHEET_ID';
const SHEET_NAME = 'Sheet1';
const SUPPORT_SENDER_NAME = 'Support Team';
const SUPPORT_FROM_EMAIL = ''; // Optional: set a specific from address if permitted

function doGet() {
  // Serves the form HTML
  return HtmlService.createHtmlOutputFromFile('index')
    .setTitle('AI Support Ticket');
}

/**
 * Called from client to create the ticket.
 * formData: { name, email, message }
 */
function processTicket(formData) {
  try {
    if (!formData || !formData.email || !formData.message) {
      throw new Error('Missing required fields');
    }

    const openaiKey = PropertiesService.getScriptProperties().getProperty(OPENAI_KEY_PROP);
    const spreadsheetId = PropertiesService.getScriptProperties().getProperty(SPREADSHEET_ID_PROP);
    if (!openaiKey) throw new Error('OpenAI key not set. Use Project Properties or setOpenAIKey()');
    if (!spreadsheetId) throw new Error('Spreadsheet ID not set. Use Project Properties or setSpreadsheetId()');

    // 1) Call OpenAI (chat completion expecting JSON output)
    const openaiUrl = 'https://api.openai.com/v1/chat/completions';
    const promptMessages = [
      {
        role: 'system',
        content: 'Return ONLY valid JSON with these fields: { "summary": "...", "category": "Billing|Technical|Account|General", "urgency": "Low|Medium|High", "draft_reply": "..." }'
      },
      {
        role: 'user',
        content: `Name:${formData.name}\nEmail:${formData.email}\nIssue:${formData.message}`
      }
    ];

    const payload = {
      model: 'gpt-4o-mini', // adjust model as needed
      messages: promptMessages,
      temperature: 0.2,
      max_tokens: 600
    };

    const options = {
      method: 'post',
      contentType: 'application/json',
      headers: {
        Authorization: 'Bearer ' + openaiKey
      },
      payload: JSON.stringify(payload),
      muteHttpExceptions: true
    };

    const resp = UrlFetchApp.fetch(openaiUrl, options);
    const code = resp.getResponseCode();
    if (code < 200 || code >= 300) {
      throw new Error('OpenAI request failed: ' + resp.getContentText());
    }

    const aiJson = JSON.parse(resp.getContentText());
    const aiMessage = aiJson.choices && aiJson.choices[0] && aiJson.choices[0].message && aiJson.choices[0].message.content;
    if (!aiMessage) throw new Error('No assistant content returned');

    // The assistant is instructed to return JSON only; try to parse it
    let aiOutput;
    try {
      aiOutput = JSON.parse(aiMessage);
    } catch (err) {
      // If parsing fails, wrap the raw content as a fallback
      aiOutput = {
        summary: aiMessage.substring(0, 1000),
        category: 'General',
        urgency: 'Medium',
        draft_reply: aiMessage
      };
    }

    // 2) Append to spreadsheet
    const ss = SpreadsheetApp.openById(spreadsheetId);
    const sheet = ss.getSheetByName(SHEET_NAME) || ss.insertSheet(SHEET_NAME);
    sheet.appendRow([
      new Date(),
      formData.name || '',
      formData.email || '',
      formData.message || '',
      aiOutput.summary || '',
      aiOutput.category || '',
      aiOutput.urgency || ''
    ]);

    // 3) Send email (or create draft)
    const subject = `Support request received — ${aiOutput.category || 'General'}`;
    const plainBody = (aiOutput.draft_reply || '')
      + '\n\n--\nThis is an automated reply generated by AI.';

    // Option A: send immediately
    GmailApp.sendEmail(formData.email, subject, plainBody, {
      name: SUPPORT_SENDER_NAME
      // from: SUPPORT_FROM_EMAIL // Uncomment if you have a delegated send-as address
    });

    // Option B: create draft instead of sending (comment out sendEmail above and uncomment below)
    // GmailApp.createDraft(formData.email, subject, plainBody, {name: SUPPORT_SENDER_NAME});

    return {
      status: 'OK',
      summary: aiOutput.summary,
      category: aiOutput.category,
      urgency: aiOutput.urgency,
      draft_reply: aiOutput.draft_reply
    };
  } catch (err) {
    // Log and return error to client
    console.error(err);
    return { status: 'ERROR', message: err.message || String(err) };
  }
}

/**
 * Utility functions (run from script editor if you want to set props)
 */
function setOpenAIKey(key) {
  PropertiesService.getScriptProperties().setProperty(OPENAI_KEY_PROP, key);
}
function setSpreadsheetId(id) {
  PropertiesService.getScriptProperties().setProperty(SPREADSHEET_ID_PROP, id);
}
